# gen-web-assets.ps1 — embed the settings SPA into the firmware.
#
# Gzip-compresses web/index.html and writes web_assets.h: a PROGMEM byte
# array the HTTP server serves with `Content-Encoding: gzip`. The header
# is committed to the repo so the arduino-cli build needs no extra step
# — run this only after editing web/index.html.
#
#   pwsh tools/gen-web-assets.ps1
#
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$root = Split-Path $PSScriptRoot -Parent
$src  = Join-Path $root 'web/index.html'
$dst  = Join-Path $root 'web_assets.h'

if (-not (Test-Path $src)) {
    Write-Error "[gen-web-assets] source not found: $src"
}

$raw = [System.IO.File]::ReadAllBytes($src)

# Gzip in memory at maximum compression.
$ms = [System.IO.MemoryStream]::new()
$gz = [System.IO.Compression.GzipStream]::new(
        $ms, [System.IO.Compression.CompressionLevel]::Optimal)
$gz.Write($raw, 0, $raw.Length)
$gz.Dispose()
$bytes = $ms.ToArray()
$ms.Dispose()

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// web_assets.h — GENERATED by tools/gen-web-assets.ps1. Do not edit by hand.')
[void]$sb.AppendLine('//')
[void]$sb.AppendLine('// The settings SPA (web/index.html), gzip-compressed and embedded in')
[void]$sb.AppendLine('// PROGMEM. http_server.cpp serves it at / with Content-Encoding: gzip.')
[void]$sb.AppendLine('// Regenerate after editing the page:  pwsh tools/gen-web-assets.ps1')
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('#include <pgmspace.h>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine("// $($raw.Length) bytes HTML -> $($bytes.Length) bytes gzip")
[void]$sb.AppendLine("static const unsigned int WEB_INDEX_HTML_GZ_LEN = $($bytes.Length);")
[void]$sb.AppendLine('static const unsigned char WEB_INDEX_HTML_GZ[] PROGMEM = {')
for ($i = 0; $i -lt $bytes.Length; $i += 16) {
    $end  = [Math]::Min($i + 16, $bytes.Length)
    $line = '  '
    for ($j = $i; $j -lt $end; $j++) {
        $line += '0x{0:x2},' -f $bytes[$j]
    }
    [void]$sb.AppendLine($line)
}
[void]$sb.AppendLine('};')

[System.IO.File]::WriteAllText($dst, $sb.ToString())
Write-Host ("[gen-web-assets] {0} B HTML -> {1} B gzip -> web_assets.h" `
            -f $raw.Length, $bytes.Length)
